# Generated by Django 3.0.3 on 2020-03-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=86)),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
                ('pro', models.IntegerField(default=0)),
                ('contra', models.IntegerField(default=0)),
                ('rank', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wann', models.DateTimeField(auto_now_add=True)),
                ('von', models.EmailField(max_length=254)),
                ('grund', models.CharField(max_length=95)),
                ('nachricht', models.TextField()),
            ],
        ),
    ]
